version: '3.10'

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    restart: always
    ports:
      - "5432:5432"
