version: '3.10'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
    restart: always
    ports:
      - "5432:5432"
